### ISSUE TITLE
keypoints problem

### ISSUE THREAD

**Issue by siangyang** [gazeai/STDN-PyTorch#1]
Hi,
I want to ask what kind of data the keypoints should be in the data preparation part.

Thanks!!

**Comment by rupaai** [comment]
In the original implementation, they had [68 keypoints](https://github.com/yaojieliu/ECCV20-STDN/blob/master/data/train/spoof/1/1.npy) for each face. For extracting the keypoints, they used the following repository:
https://github.com/yaojieliu/ICCVW2017-DenseFaceAlignment
However, for my own convenience, I used the following repository to extract the landmarks:
https://github.com/cunjian/pytorch_face_landmark

hope It helps.
